name: Build EXE with Auto-py-to-exe
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          poetry-version: 1.3.2
          
      - name: Install dependencies
        run: poetry install

      - name: Install dependencies
        run: |
          pip install auto-py-to-exe

      - name: Build EXE with auto-py-to-exe
        run: python -m auto_py_to_exe --noconsole --onefile --input src/main.py --output dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: dist/
