name: Build EXE
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          poetry-version: 1.3.2
      - name: Install dependencies
        run: poetry install
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile --noconsole src/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: dist/
