name: Build EXE
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Шаг 3: Установка Poetry вручную
      - name: Install Poetry
        run: |
          pip install poetry
          echo "$(pip show poetry | grep Location | awk '{print $2}')/Scripts" >> $GITHUB_ENV

      # Шаг 4: Проверка доступности Poetry
      - name: Verify Poetry installation
        run: poetry --version

      # Шаг 5: Установка зависимостей через Poetry
      - name: Install dependencies
        run: |
          poetry add html2text==2024.2.26 pre-commit==4.0.1 pydantic==2.10.1 wxpython==4.2.2
          poetry install
          pip install pyinstaller
          pip install typing_extensions

      # Шаг 6: Сборка EXE файла через PyInstaller
      - name: Build EXE
        run: pyinstaller --onefile --noconsole src/main.py

      # Шаг 7: Загрузка артефактов
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: dist/
